name: SAFE Template release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Tool Restore
        run: dotnet tool restore

      - name: Release
        env:
          VERSION: ${{ github.ref_name }}
          RELEASE_NOTES_URL: ${{ github.event.release.html_url }}
          RELEASE_NOTES_BODY: ${{ github.event.release.body }}
          NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
        run: dotnet run --project Build.fsproj -- Release

#      - name: Update Release notes
#        env:
#            VERSION: ${{ github.ref_name }}
#            RELEASE_NOTES_BODY: ${{ github.event.release.body }}
#        run: dotnet run --project Build.fsproj -- UpdateReleaseNotes


      - name: Commit and push Release Notes
        uses: actions-js/push@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'master'
            message: ${{ format( 'Release {0} 🚀', github.ref_name) }}